/*
 * Copyright (c) 2020 Salt Edge Inc.
 */
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'idea'

def libVersionCode = 1
def libVersionName = "1.0.0"

android {
    defaultConfig {
        minSdkVersion 19
        compileSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
    namespace 'com.saltedge.android.security'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test:runner:1.5.2'
}
