apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    defaultConfig {
        minSdkVersion 21
        compileSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.saltedge.android.test_tools'
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    api ('com.saltedge.authenticator:sdk_core:1.3.2@aar')
    implementation ('com.saltedge.authenticator:sdk_v1:1.6.1@aar')
    implementation ('com.saltedge.authenticator:sdk_v2:2.4.1@aar') {
        transitive = true
    }

    api 'junit:junit:4.13.2'
    api 'androidx.test:core:1.5.0'
    api 'androidx.arch.core:core-testing:2.2.0'
    api 'androidx.test.ext:junit:1.1.5'
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3'
    api 'org.mockito.kotlin:mockito-kotlin:3.2.0'

}
